# Generated by Django 3.0.7 on 2020-08-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
